# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Replace Analytics ID"
        run: sed -i "s/GOOGLE_ANALYTICS_ID/${{secrets.GCP_ANALYTICS_ID}}/g" $GITHUB_WORKSPACE/src/main.js
      
      - name: Yarn CLI        
        uses: CultureHQ/actions-yarn@v1.0.1
        
      - name: Installing dependencies
        run: yarn install
        
      - name: Building application
        run: yarn build --mode production

      - name: Push to GCR Github Action
        uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          gcloud_service_key: ${{secrets.GCP_SERVICEKEY}}
          project_id: ${{secrets.GCP_PROJECT}}
          image_name: simpleks-frontend
          image_tag: latest          
         
      - name: Cloud Run
        uses: stefda/action-cloud-run@v1.0
        with:
          # Name of the docker image
          image: gcr.io/${{secrets.GCP_PROJECT}}/simpleks-frontend:latest
          # Name of the service in Cloud Run
          service: ${{secrets.GCP_SERVICE}}
          # GCP project
          project: ${{secrets.GCP_PROJECT}}
          # GCP region
          region: ${{secrets.GCP_REGION}}
          # GCP service key with storage and run permissions
          service key: ${{secrets.GCP_SERVICEKEY}}
      
